### ISSUE TITLE
Mac version don't have perm to download or save file.

### ISSUE THREAD

**Issue by HydrolienF** [HydrolienF/Formiko#393]
**Describe the bug**
Even if wifi is on & working, jar file can't download anything.

**To Reproduce**
1. Use last release for max.

**Expected behavior**
We need to have : 
- [x] the ability to download file
- [x] a simpler app for mac as .msi for Windows.
- [x] full screen issues

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 2.0

**Comment by Mistis0** [comment]
What I need to do to use formiko on MacOS:
1. download Formiko2.21.80Mac
2. chmod 700 formiko.command
3. formiko.command can't be open by double clic because it isn't run in curent folder & fail to find java
4. It can be launch on command line & print color + the download frame.
5. Download end but I can't find downloaded file. So maybe it is not created because download is forbidden or mkdir fail.
6. game try to fix itself by retry download, fail 3 or 4 times & go down because data are missing.

7.sudo don't fix it

**Comment by Mistis0** [comment]
mac version can downloa file & work with launcher formiko.command

**Comment by Mistis0** [comment]
Mac version still need a fix for full screen that stay black for me.
